### ISSUE TITLE
problems in wifiroaming.py example forunbound method intfName()

### ISSUE THREAD

**Issue by visenchou** [dlinknctu/OpenNet#11]
Hello sir,
    When I input the last instruction : sudo ./waf --pyrun ../../../mininet/examples/wifiroaming.py , It shows 

Waf: Entering directory `/home/zhouys/repos/ns-3-allinone/ns-3.18/build'
Waf: Leaving directory`/home/zhouys/repos/ns-3-allinone/ns-3.18/build'
'build' finished successfully (1.320s)

Modules built:
antenna                   aodv                      applications  
bridge                    buildings                 config-store  
core                      csma                      csma-layout  
dsdv                      dsr                       emu  
energy                    fd-net-device             flow-monitor  
internet                  lte                       mesh  
mobility                  mpi                       netanim  
network                   nix-vector-routing        olsr  
point-to-point            point-to-point-layout     propagation  
spectrum                  stats                     tap-bridge  
test (no Python)          topology-read             uan  
virtual-net-device        visualizer                wifi  
wimax                    

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     openflow                 

**\* Adding controller
Traceback (most recent call last):
  File "../../../mininet/examples/wifiroaming.py", line 154, in <module>
    WifiNet()
  File "../../../mininet/examples/wifiroaming.py", line 119, in WifiNet
    tb = addfunc (node, wichannel, wissid)
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 491, in addSta

  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 446, in add

TypeError: unbound method intfName() must be called with Link instance as first argument (got Host instance instead)
Command ['/usr/bin/python', '../../../mininet/examples/wifiroaming.py'] exited with code 1

what is wrong with it ?
could do do me a favor ?
thank you!

**Comment by kansokusha** [comment]
Hello, this problem is because ns-3 remove the static property of intfName().
Please checkout our dev branch, we have updated the ns-3 version and wifiroaming.py for this issue.

**Comment by visenchou** [comment]
Hi, sir, thank you for your help. I followed your advice, and then I got another problem like this 

root@zhouys-OptiPlex-9010:~/mininet/examples# python wifiroaming.py 
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
Traceback (most recent call last):
  File "wifiroaming.py", line 167, in <module>
    WifiNet()
  File "wifiroaming.py", line 129, in WifiNet
    tb = addfunc (node, wichannel, wissid)
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 828, in addSta
    
AttributeError: type object 'wifi.StaWifiMac' has no attribute 'ACTIVE'
root@zhouys-OptiPlex-9010:~/mininet/examples# 

in addition, I use the master branch install the OpenNet in the ubuntu14.04 X86 instead of Virtualbox.
I installed this step by step, but it failed in the last step when I test the wifiroaming.py.
hope for your help, thank you!

**Comment by kansokusha** [comment]
Our wifiroaming.py example in the dev branch works on ns-3.21 and Mininet 2.2.0b3.
Please refer to the dev branch installation instruction.

There are two errors when running this script.
1. Unable to contact the remote controller at 127.0.0.1:6633
This script requires a controller which is running at 127.0.0.1:6633.
2. AttributeError: type object 'wifi.StaWifiMac' has no attribute 'ACTIVE'
OpenNet has some features need ns-3 python API scan to make them work with ns-3.

**Comment by visenchou** [comment]
thanks, but i still don't know how to set a controller running at 127.0.0.1:6633, meanwhile, can I install the OpenNet in ubuntu directly?  In addition, I install mininet2.2.0 by the link http://downloads.mininet.org/mininet-2.2.0-150106-ubuntu-14.04-server-i386.zip  , and I make sure that Python API Scanning Support   : enabled 
what should I do ?  thank you!

**Comment by visenchou** [comment]
hello, I install it through the dev branch with ns-3.21 and mininet 2.2.0b2  as this link says https://github.com/dlinknctu/OpenNet/tree/dev   ,but it failed when I input this command  : 
$ sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
$ sudo systemctl stop firewalld.service
$ sudo systemctl disable firewalld.service
$ sudo setenforce 0
$ sudo systemctl enable openvwitch.service
$ sudo systemctl start openvswitch.service

e.g  there isn't 'config' in the '/etc/selinux' when I input  $  sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
so, I ignore all these commands and input the following commands, which did not output other faults.
But when I test the last command ： $ python wifiroaming.py   it failed  with the fault below 

zhouys@zhouys-OptiPlex-9010:~/repos/mininet/examples$ python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core
zhouys@zhouys-OptiPlex-9010:~/repos/mininet/examples$ sudo python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core

How should I do? Thank you!

**Comment by kansokusha** [comment]
You can run any controller has L2 learning capability at 127.0.0.1:6633.
Take POX as example: $ ./pox.py forwarding.l2_learning

Please make sure your environment use ns-3.21 and Mininet 2.2.0b3.
Because ns-3.21 has some issue on Ubuntu, we currently support Fedora.

Besides enable python API scanning support, an successful API scanning such as: $ ./waf --apiscan=wifi is required.

**Comment by visenchou** [comment]
Hi, I install ns-3.18 in the ubuntu 14.04, and I have worked step by step as tutorial says to install and test the ns-3. But when I test my ns-3 using ./test.py, it turned out to be wrong as follows: 

......
PASS: TestSuite ns3-tcp-state
SKIP: TestSuite nsc-tcp-loss
PASS: TestSuite ns3-tcp-loss
PASS: TestSuite lte-x2-handover
PASS: TestSuite lte-x2-handover-measures
159 of 163 tests passed (159 passed, 3 skipped, 0 failed, 1 crashed, 0 valgrind errors)
zhouys@zhouys-OptiPlex-9010:~/workspace_ns3.18/ns-allinone-3.18/ns-3.18$ 

I check 1 crashed and 3 skipped tests as follows
CRASH: TestSuite devices-mesh-dot11s-regression
SKIP: TestSuite ns3-tcp-cwnd
SKIP: TestSuite ns3-tcp-interoperability
SKIP: TestSuite nsc-tcp-loss

I want to install the OpenNet by using this ns-3.18 and mininet. So, I want to know how to solve this problem and whether this error is the reason affecting the OpenNet installation. Could you do me a favor? Thanks

**Comment by visenchou** [comment]
Hello sir,
I install it through the dev branch with ns-3.18 and mininet 2.2.0b3 in Ubuntu 14.04
When I input the last instruction : sudo ./waf --pyrun ../../../mininet/examples/wifiroaming.py , It shows
*** Adding controller
Traceback (most recent call last):
File "../../../mininet/examples/wifiroaming.py", line 154, in 
WifiNet()
File "../../../mininet/examples/wifiroaming.py", line 119, in WifiNet
tb = addfunc (node, wichannel, wissid)
File "build/bdist.linux-i686/egg/mininet/ns3.py", line 491, in addSta

File "build/bdist.linux-i686/egg/mininet/ns3.py", line 446, in add

TypeError: unbound method intfName() must be called with Link instance as first argument (got Host instance instead)
Command ['/usr/bin/python', '../../../mininet/examples/wifiroaming.py'] exited with code 1

I did not change any step in the link https://github.com/dlinknctu/OpenNet/tree/master .
is there anything wrong with it? I tried lots of times to install it, while they all failed. would you please show me the wrong with me ?  should I use other files or steps without show in that pages https://github.com/dlinknctu/OpenNet/tree/master . 
Thank you for you help

**Comment by rascov** [comment]
For now, we only have tested
ns 3.18 + mininet 2.0.0 + opennet master
ns 3.21 + mininet 2.2.0 + opennet dev
I will merge dev to master soon, and update README accordingly.
Sorry for the inconvenience.

**Comment by visenchou** [comment]
Thank you for your suggestion, and  can I just install OpenNet in the Ubuntu 14.04 instead of Virtual box, meanwhile I want to configure that you tested by ns 3.18 + mininet 2.0.0 + opennet master without using other files or patches such as '  tap-bridge.cc.patch ' . Thank you again!

**Comment by rascov** [comment]
We currently maintain 1.0 branch only.
Therefore, I strongly recommend you use follow the instructions in the README of master branch.

If you still want to try the older version, please follow the steps on the 1.0 branch.
You will need all patches listed in the README of 1.0 branch.

**Comment by visenchou** [comment]
Thank you for your advice, then I'm going to follow the master branch to install the OpenNet. I want to ask you whether it can work in Fedora-i686 or ubuntu14.04 x86. Thank you for your patient

**Comment by rascov** [comment]
We have successfully installed ns-3.21 on Fedora only.
We encountered the following bug when testing on Ubuntu. It seems to be unresolved.
https://www.nsnam.org/bugzilla/show_bug.cgi?id=1990

**Comment by visenchou** [comment]
Thank you for your help, I just install it in Fedora 21 3.17.4-301.fc21.x86_64, I worked through all the step as the master branch says except the last step 'python wifiroaming.py', it tured out to be wrong as follows:

[zhouys@localhost ns-3.21]$ sudo python ../../mininet/examples/wifiroaming.py 
Traceback (most recent call last):
  File "../../mininet/examples/wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-x86_64/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core

then I input another command to test it ‘ sudo ./waf --pyrun ../../mininet/examples/wifiroaming.py  ’.

[zhouys@localhost ns-3.21]$ sudo ./waf --pyrun ../../mininet/examples/wifiroaming.py 
Waf: Entering directory `/home/zhouys/ns-allinone-3.21/ns-3.21/build'
Waf: Leaving directory `/home/zhouys/ns-allinone-3.21/ns-3.21/build'
'build' finished successfully (0.743s)

Modules built:
antenna                   aodv                      applications             
bridge                    buildings                 config-store             
core                      csma                      csma-layout              
dsdv                      dsr                       emu                      
energy                    fd-net-device             flow-monitor             
internet                  lr-wpan                   lte                      
mesh                      mobility                  mpi                      
netanim                   network                   nix-vector-routing       
olsr                      point-to-point            point-to-point-layout    
propagation               sixlowpan                 spectrum                 
stats                     tap-bridge                test (no Python)         
topology-read             uan                       virtual-net-device       
wave                      wifi                      wimax                    

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     openflow                 
visualizer               

*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
*** Starting network
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 7 switches
s1 s2 s3 s4 s5 s6 s7 
Testing network connectivity
*** h1 : ('ping 10.10.10.2 -c 3',)
PING 10.10.10.2 (10.10.10.2) 56(84) bytes of data.
From 10.10.10.1 icmp_seq=1 Destination Host Unreachable
From 10.10.10.1 icmp_seq=2 Destination Host Unreachable
From 10.10.10.1 icmp_seq=3 Destination Host Unreachable

--- 10.10.10.2 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2000ms
pipe 3
*** Starting CLI:
mininet>

In addition, when I patched ns3 ,I just input the command as follows:
$ patch -p1 < animation-interface.patch
$ patch -p1 < netanim-python.patch
$ patch -p1 < sta-wifi-scan.patch
Should I patch the 'tap-bridge-offset.patch', while it did not show anything wrong have relationship with 'tap-bridge-offset.patch'.

Would you please tell me the wrong with it? Thank you for you help.

**Comment by visenchou** [comment]
Hi, sir, there is another problem I don't know whether it will affect the result. It shows as follows:

[zhouys@localhost ns-3.21]$ sudo setenforce 0
setenforce: SELinux is disabled
[zhouys@localhost ns-3.21]$ sudo systemctl enable openvwitch.service
Failed to execute operation: No such file or directory

what's wrong with this question and above question. Could you do me a favor?

**Comment by rascov** [comment]
The 'python wifiroaming.py' should be run under waf shell. Please make sure you already run './waf shell' 
(Alternatively, your approach works too.)

You don't need tap-bridge-offset.patch for ns-3.21. That is an old patch for 3.18 and already removed from our repository. (We only have 3 patches in ns3-patch directory)

**Comment by visenchou** [comment]
Thank you for your answer, I have run './waf shell' as the tutorial says, but it still turned out to be wrong. I still want to know whether it will affect the result when I input these commands.

[zhouys@localhost ns-3.21]$ sudo setenforce 0
setenforce: SELinux is disabled
[zhouys@localhost ns-3.21]$ sudo systemctl enable openvwitch.service
Failed to execute operation: No such file or directory
Can I just install it step by step without any other Accessory? Could you show me how to solve my problems? Thank you!

**Comment by kansokusha** [comment]
With the following command in the mater branch: $ sudo util/install.sh -fnpv,
we have installed some components with the Mininet.
 -p: install (P)OX OpenFlow Controller
 -v: install Open (V)switch

The first "Destination Host Unreachable" question occurs with the statement:
"Unable to contact the remote controller at 127.0.0.1:6633".

We have installed a controller called POX with the Mininet,
it can be used to solve the problem:
$ cd pox
$ python pox.py forwarding.l2_learning

For the second question,
$ sudo setenforce 0
setenforce: SELinux is disabled
This state shows SELinux is disabled, which is required for the OpenNet,
or more preciously, for the Open vSwitch.

$ sudo systemctl enable openvwitch.service
Failed to execute operation: No such file or directory
This statement may shows some problems, at first, there is a typo in the command.

Please check the following two commands:
$ sudo systemctl enable openvswitch.service
If the service has been enabled, this line should works without output.

$ sudo systemctl status openvwitch.service
The output should shows the active status.
● openvswitch.service - Open vSwitch
   Loaded: loaded (/usr/lib/systemd/system/openvswitch.service; enabled)
   Active: active (exited) since Sun 2015-01-18 16:01:01 CST; 58s ago

Otherwise, please try to reinstall the Open vSwitch.

**Comment by visenchou** [comment]
Thank you very much! I have solved it.

**Comment by wicosh** [comment]
Hi,there.I have built ns-3.22,but I got the same error as visenchou after ran ./test.py.
SKIP: TestSuite ns3-tcp-cwnd
SKIP: TestSuite ns3-tcp-interoperability
SKIP: TestSuite nsc-tcp-loss
How can I fix it?

Regards

**Comment by pichuang** [comment]
We will handle that as soon as possible.

**Comment by PhDstudent26** [comment]
Goof afternoon,
I installed opennet. But when I usethe command  python ../wifiroaming.py the ping failed 
I installed ruy to create a controller. Unfortunately, I tried  there are problems. I run (ryu_venv)$ ryu-manager ./ryu/ryu/ryu/app/simple_switch_13.py  The message "instantiating app ryu/app/simple_switch_13.py of SimpleSwitch13" appeared, then no thing was happened. 
I use the command ryu-manager --ofp-tcp-listen-port 5555 --verbose (to modify the port instead of 6633). but when I use the command python ../roaming.py,  I have always the same problem the ping  failed:
*** Adding controller
Wifi pcap path: /tmp/pcap/wifi
CSMA pcap path:/tmp/pcap/csma
Netanim path: /tmp/xml/wifi-wired-bridged4.xml
*** Starting network
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 7 switches
s1 s2 s3 s4 s5 s6 s7 ...
Testing network connectivity
*** h1 : ('ping 10.10.10.2 -c 3',)
PING 10.10.10.2 (10.10.10.2) 56(84) bytes of data.
From 10.10.10.1 icmp_seq=1 Destination Host Unreachable
From 10.10.10.1 icmp_seq=2 Destination Host Unreachable
From 10.10.10.1 icmp_seq=3 Destination Host Unreachable

--- 10.10.10.2 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2000ms
pipe 3
*** Starting CLI:
opennet> Max Packets per trace file exceeded

**Comment by rascov** [comment]
Hi,

Here are something you can try while troubleshooting.

1. Check the connectivity between switch and controller
If you are using OVS, you can check the "isConnected" value in the result
of "ovs-vsctl show" command

2. Do a packet dump on the network and see where the problem is

Cheers,

Charles

**Comment by PhDstudent26** [comment]
hi, 
Thank you for you response. I didn't find the isConnected value after running ovs-vsctl show. I installed ubuntu 14.04 on virtualbox and then I tried to install Opennet using these commands :  git clone https://github.com/dlinknctu/OpenNet.git and  sudo ./install.sh -a.    the versions mentioned in the install.sh file are ns-3.22 and mininet 2.2.1 and ovs 2.4.0. I tried many times to correct the different errors but they always exist. when I run the wifiroaming.py there is a problem of connection to the remote control at 127.0.0.1:6633.
I used mn -c and I runned the examples of   the directory /mininet/examples/ns3. The transmitted packets are received then the message starting CLI  and opennet> appeared 
In this case, opennet is installed correctly or Not. Excuse me for these questions. I don't have no ideas about this simulator

**Comment by kansokusha** [comment]
Hello, PhDstudent26.
Please use the same issue list, this can make us easier to track the issue.

Successfully running of examples in /mininet/examples/ns3 means OpenNet is installed correctly.
In the case of wifiroaming.py, this example requires an SDN controller to control the network forwarding mechanism. 

There is a simple controller called POX.
You can install and run that controller through following commands:
$ git clone https://github.com/noxrepo/pox.git
$ ./pox/pox.py forwarding.l2_learning

While running the SDN controller in a terminal, try to execute wifiroaming.py in another.
The issue, "Unable to contact the remote controller", should be resolved.

If the example still can not receive packets, please check the output of controller.

**Comment by PhDstudent26** [comment]
Good evening,
thank you for the response and excuse me for posting here my question. I installed pox and I run it and  the wifiroaming file in two separate terminals. the packets are not received and in the pox terminal I obtained the following output:
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
INFO:packet:(ipv6) warning IP packet data incomplete (114 of 287)
INFO:packet:(dns) parsing questions: incomplete name
INFO:packet:(ipv6) warning IP packet data incomplete (114 of 211)
INFO:packet:(dns) parsing answers: next_rr: data truncated
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86

Is it necessary to run the wifiroaming file. It has any relation with running other files?

**Comment by kansokusha** [comment]
It seems that the example script failed to attach the controller.
Here comes another way to run the example script.

Execute the wifiroaming.py in a terminal, then start POX in another.
In the script terminal, it will prompt: "Unable to contact the remote controller".

Run POX controller via following command:
./pox/pox.py log.level --WARNING --forwarding=DEBUG --openflow=DEBUG forwarding.l2_learning

POX shall print some logs, which indicate the script has attached to the controller:
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-03 3]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-05 1]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-07 4]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-04 2]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-02 5]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-06 6]
DEBUG:forwarding.l2_learning:Connection [00-00-00-00-00-01 7]

Back to the script terminal, type "pingall".
This time, the ping test should work.

**Comment by PhDstudent26** [comment]
Hi,
I tried again to run the wifiroaming.py with pox. I obtained in error in the terminal script:
Traceback (most recent call last):
File "wifiroaming.py", line 14, in 
import mininet.ns3
File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in 
ImportError: No module named ns.core
In the terminal of pox controller I obtained :
POX shall print some logs, which indicate the script has attached to the controller:
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO: core:POX 0.2.0 (carp) is up /  Copyright 2011-2013 James McCauley, et al.
INFO: openflow.of_01 [00-00-00-00-00-07 1] connected
INFO: openflow.of_01 [00-00-00-00-00-01 2] connected
INFO: openflow.of_01 [00-00-00-00-00-06 3] connected
INFO: openflow.of_01 [00-00-00-00-00-05 7] connected
INFO: openflow.of_01 [00-00-00-00-00-03 5] connected
INFO: openflow.of_01 [00-00-00-00-00-02 6] connected
INFO: openflow.of_01 [00-00-00-00-00-04 4] connected

**Comment by pichuang** [comment]
Hi,
You need run "~/opennet/waf_shell.sh" when opening new terminal.

**Comment by PhDstudent26** [comment]
Hi,
I always run ./waf_shell.sh before running the wifiroaming. py and the same problem exist.

**Comment by kansokusha** [comment]
waf_shell.sh is used to setup some environment variables, includes python import path.
"ImportError: No module named ns.core" is caused by incomplete python import path.


It seems you have successfully run the wifiroaming.py example, please check the python path again.
If this problem does not solved, scripts like /mininet/examples/ns3 still can write and test.

**Comment by PhDstudent26** [comment]
the PTYHONPATH contains the following path:
/home/student/Desktop/ns-allinone-3.22/ns-3.22/build/bindings/python:/home/student/Desktop/ns-allinone-3.22/ns-3.22/src/visualizer:/home/student/Desktop/ns-allinone-3.22/pybindgen-0.17.0.886:/home/student/Desktop/ns-allinone-3.22/ns-3.22/build/bindings/python:/home/student/Desktop/ns-allinone-3.22/ns-3.22/src/visualizer:/home/student/Desktop/ns-allinone-3.22/pybindgen-0.17.0.886
I tried to run a script from the mininet/examples/ns3 but the same error "ImportError: No module named ns.core" appears.

**Comment by kansokusha** [comment]
Please make sure your environment has "ns3.py" and an "ns" directory under the following path: /home/student/Desktop/ns-allinone-3.22/ns-3.22/build/bindings/python.
Proper access permission to "ns3.py" and "ns" directory is also required.

**Comment by PhDstudent26** [comment]
tns3.py and  ns exist under the mentioned path. I verified that the access permission exist

**Comment by kansokusha** [comment]
Based on the #67, it seems that wifiroaming.py can be executed in your environments.
The problem is packets can not be forwarded without the SDN controller.
But this time, the problem turns into the python import error.

Except wifiroaming.py, examples under the /mininet/examples/ns3 can be executed in current environment?
If not, please describe detailed path and commands used to run wifiroaming.py example.

**Comment by PhDstudent26** [comment]
The files in the mininet/examples/ns3 cannot be runned. To run the wifiroaming.py, I used the following commands
$cd Desktop 
$ sudo ./waf_shell.sh
$ sudo python /home/student/Desktop/mininet/examples/opennet/wifiroaming.py

**Comment by kansokusha** [comment]
At the last command, "sudo" will make python use another set of the environment variables.
Remove "sudo" from that command can avoid the import error.

After wifiroaming.py shows "opennet>" prompt, launch the pox controller via
"./pox/pox.py log.level --WARNING --forwarding=DEBUG --openflow=DEBUG forwarding.l2_learning"
, then type "pingall" in the script terminal.
If the script attaches to the controller correctly and makes a successful ping test,
the controller will print some information like below: 
DEBUG:forwarding.l2_learning:installing flow for c6:9a:dc:1c:c4:0c.1 -> 56:73:67:be:54:19.2
DEBUG:forwarding.l2_learning:installing flow for c6:9a:dc:1c:c4:0c.3 -> 56:73:67:be:54:19.1

**Comment by PhDstudent26** [comment]
when I remove sudo anf I run wifiroaming.py, there is always a message: mininet must run as root

**Comment by kansokusha** [comment]
waf_shell.sh is a helper to setup the environment variable, execute waf_shell.sh is always required.
Here are some screenshots about running the simulation, please refer these steps.
If the script does not attach to the controller successfully, use "sudo mn -c" to clear the virtual interfaces created by the simulation and try again.
1.
![walkthrough1](https://cloud.githubusercontent.com/assets/2024544/11200118/20431064-8d0e-11e5-8995-dc3c03dd8dbf.PNG)
2.
![walkthrough2](https://cloud.githubusercontent.com/assets/2024544/11200121/27bc3992-8d0e-11e5-9250-cdbe5c3485f7.PNG)
3.
![walkthrough3](https://cloud.githubusercontent.com/assets/2024544/11200123/2c14da30-8d0e-11e5-8247-fdcdcebde97f.PNG)
4.
![walkthrough4](https://cloud.githubusercontent.com/assets/2024544/11200128/302a9218-8d0e-11e5-97bf-8a8409d981c3.PNG)

**Comment by PhDstudent26** [comment]
Unfortunately, I repeat many times the instructions and I reinstall pox and openNet but the same problem exists (packets are not received when running the wifiroaming.py). The files of the ns3 folder are runned with success. Would you please tell me if there is a tutorial that explains how to write scripts under openNet?

**Comment by kansokusha** [comment]
Sorry for that we do not have a formal tutorial about how to write simulation scripts.
It is possible to use the classes in ns-3, just like the examples under mininet/examples/ns3.

If only uses part of the OpenNet as ns-3 with python binding, [tutorial](https://www.nsnam.org/docs/manual/html/python.html) about how to write ns-3 scripts may help.

**Comment by PhDstudent26** [comment]
I want to simulate a wireless SDN controller with mobile nodes in an ad hoc environement. I use opennet instead of ns-3 because ns-3 does not support wireless SDN. In this case, I must write scripts like the mininet scripts or the ns-3 scripts with python?

**Comment by kansokusha** [comment]
In this case, the script will like mininet scripts.
Example about ad hoc simulation can be found under mininet/examples/ns3.
wifiroaming.py is our example for the following scenario: a out-of-band SDN controller controls packet forwarding mechanism between WiFi access points and stations.
For the controller issue, maybe get familiar with Open vSwitch, Mininet and SDN controller may help to solve it.

**Comment by PhDstudent26** [comment]
Can I import any module from ns3 through the instruction from mininet.ns3 import * (example lte, wave,  mobility,...) and adding devices to nodes like in NS-3. Can I also use a tracefile that contains the informations about the nodes generated by a generator of mobility (such as mobisim or sumo)?

**Comment by kansokusha** [comment]
Yes, ns-3 modules can be imported as you said, but we only support an easy-to-use WiFi interface.
If you want to use other modules in the script, these modules may make the script a little complicated.
Applications can be executed on the virtual nodes in the simulation, but it requires user have some knowledge about Linux Container and Mininet.

**Comment by PhDstudent26** [comment]
Good afternoon,
Is it possible to establish a communication between nodes (created by ns3: nodecontainer instead of the node module of mininet) and a SDN controller in openNet? Can you please explain me more about  this "Applications can be executed on the virtual nodes in the simulation, but it requires user have some knowledge about Linux Container and Mininet."

**Comment by kansokusha** [comment]
In order to connect to SDN controller, Mininet node is required.
Maybe study some Mininet tutorials can help to solve the controller attachment issue.

Sorry for misunderstanding, assign the mobility model to each node is possible.
But currently we do not support the conversion between trace file (generated by mobility simulator) and ns-3 mobility model.

**Comment by gauravbatra8** [comment]
Hi Guys !! can anyone tell me if there is any command like traceroute in OpenNet ?
I want to check the path between two nodes when I ping.

**Comment by rascov** [comment]
I think it doesn't come with built-in traceroute tool. However, you can easily install that on the mininet machine. For ubuntu just do "apt-get update && apt-get install traceroute"

**Comment by gauravbatra8** [comment]
Ok thanks I will try this.

**Comment by gauravbatra8** [comment]
Hii I installed traceroute in ubuntu. But when I work with OpenNet , it
says unknown command.

**Comment by pichuang** [comment]
@gauravbatra8  Hi I think you need to implement new function in [cli.py/mininet](https://github.com/mininet/mininet/blob/master/mininet/cli.py).

**Comment by kansokusha** [comment]
@gauravbatra8 
Hi, after install traceroute according to commands provided by rascov, your host should support traceroute command.
Here is an example about how to use traceroute in OpenNet:
In order to trace the route between Host 1 (h1) and Host 2 (h2), type "h1 traceroute h2" in OpenNet command line interface. "h1" indicates this command will be executed on Host 1, "h2" will interpreted as IP address of Host 2.
Since OpenNet is based on Mininet, Mininet tutorial is helpful to understand how to use OpenNet.

**Comment by gauravbatra8** [comment]
Great !! Its working . Thanks to all :)
